services:
  neo4j:
    image: neo4j:latest
    volumes:
      - /home/pawel/neo4j/logs:/logs
      - /home/pawel/neo4j/conf:/conf
      - /home/pawel/neo4j/data:/data
      - /home/pawel/neo4j/plugins:/plugins
    environment:
       # - NEO4J_AUTH=neo4j/your_password
        - NEO4J_PLUGINS=["apoc"]
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always